spring:
  application:
    name: ${APP_NAME:spring.kt}
  mongodb:
    host: ${MONGODB_HOST:localhost}
    port: ${MONGODB_PORT:27017}
    database: ${MONGODB_DATABASE:users}
    username: ${MONGODB_USERNAME:admin}
    password: ${MONGODB_PASSWORD:password}
    authentication-database: admin